### ISSUE TITLE
Creating an EKS cluster Failed to create with current Orb

### ISSUE THREAD

**Issue by roachmd** [pulumi/circleci#7] opened 2019-08-23 00:52 UTC
When creating and EKS cluster in AWS, I found additional items had to be installed.
I've submitted #6 to resolve this issue.

**Comment by roachmd** [comment] 2019-08-23 12:33
We probably need Orbs specific for each provider AWS, GCLOUD, ETC....

**Comment by chrsmith** [comment] 2019-08-23 15:47
Thanks for filing an issue and submitting a PR @roachmd. Though like you mentioned in the PR, it's probably too specific/opinionated. For example, it's just wasted cycles if you aren't using those cloud providers, or even if you are, you might want to use a different toolchain.

I'm inclined to think that this sort of thing -- including the dependencies for your Pulumi project -- probably doesn't belong in the Pulumi orb itself, and certainly not the `login` step. But I can definitely see the need for a general purpose orb for downloading/installing common 3rd party libraries and tools. e.g. a `install-gcloud` or `install-kubectl` command.

But even then it might make sense to put in the Pulumi orb, as Pulumi itself is a general tool that doesn't try to inject opinions about how you should be going about building or managing resources.

I'll close this issue out as "working as intended", but if you have suggestions for how we can better document how to setup an EKS cluster on CircleCI and Pulumi please do let me know.

For example, it looks like we can just add those steps from your PR in a new "example" within the orbs file? e.g. https://github.com/pulumi/circleci/blob/master/orbs/pulumi.yml#L108? That would be super-useful for other developers.

**Closed by chrsmith** 2019-08-23 15:47 UTC

**Comment by w2g-roachmd** [comment] 2019-08-23 16:05
You can use my PR steps as a new example or I can pr one for you. 

I've decided to build our own orb from this example.
